name: Generate & Build Site (Slim)

on:
  schedule:
    - cron: "0 3 * * 1,3,5"   # 월/수/금 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps for CI
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_ci.txt

      - name: Generate posts (dummy mode)
        run: |
          python site_generator/generate_posts.py --dummy --limit 10

      - name: Build site
        run: |
          python site_generator/build_site.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "auto(ci): generate & build $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
