name: Generate & Build Site (UltraSlim-SelfHeal)

on:
  schedule:
    - cron: "0 0 * * *"   # 09:00 KST
    - cron: "0 9 * * *"   # 18:00 KST
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ✅ 파일이 '없을 때만' 만들어라 (덮어쓰기 금지)
      - name: Prep repo structure (self-heal, no-overwrite)
        run: |
          mkdir -p site_generator content/keywords content/posts docs

          # generate_posts.py - 없을 때만 생성
          if [ ! -f site_generator/generate_posts.py ]; then
            cat > site_generator/generate_posts.py << 'PY'
          import os, csv, re, datetime
          POSTS_DIR="content/posts"; KEYWORDS="content/keywords/keywords.csv"
          def slugify(s):
              s=s.lower(); s=re.sub(r'[^a-z0-9ㄱ-힣\\s-]','',s); s=re.sub(r'\\s+','-',s).strip('-'); return s[:60] or "post"
          def ensure(): os.makedirs(POSTS_DIR, exist_ok=True)
          def load():
              if not os.path.exists(KEYWORDS):
                  return [("시험 공부 플래너","중학생용","informational"),
                          ("수학 공식 정리 프린트","중학 수학","informational"),
                          ("영어 단어 암기표","주 100단어","transactional")]
              out=[]; 
              with open(KEYWORDS, encoding="utf-8") as f:
                  r=csv.DictReader(f)
                  for x in r: out.append((x.get("keyword","").strip(), x.get("subtopic","").strip(), x.get("intent","informational").strip()))
              return out
          POST_HTML = """<!doctype html><meta charset="utf-8">
          <title>{title}</title><link rel="stylesheet" href="../style.css">
          <article><h1>{title}</h1><p><small>{date} · tags: auto</small></p>
          <ul><li>서브토픽: {sub}</li><li>의도: {intent}</li></ul>
          <ol><li>핵심 한 줄</li><li>오늘 액션 1개</li><li>관련 자료 추후 추가</li></ol></article>"""
          def main():
              ensure(); today=datetime.date.today().strftime("%Y-%m-%d")
              for kw,sub,intent in load()[:10]:
                  title=f"{kw} — {sub}" if sub else kw
                  slug=slugify(title)
                  html=POST_HTML.format(title=title,date=today,sub=sub,intent=intent)
                  with open(os.path.join(POSTS_DIR,f"{today}-{slug}.html"),"w",encoding="utf-8") as f: f.write(html)
              print("OK: posts generated")
          if __name__=="__main__": main()
          PY
          fi

          # build_site.py - 없을 때만 생성 (아가씨가 올린 '카드형'을 보존)
          if [ ! -f site_generator/build_site.py ]; then
            cat > site_generator/build_site.py << 'PY'
          import os, glob, datetime, shutil
          DOCS="docs"; POSTS="content/posts"
          STYLE="body{font-family:system-ui,sans-serif;max-width:840px;margin:24px auto;padding:0 12px;line-height:1.6}header,footer{opacity:.75}article{border:1px solid #eee;border-radius:12px;padding:16px;margin:18px 0}"
          def ensure():
              os.makedirs(DOCS, exist_ok=True)
              with open(os.path.join(DOCS,"style.css"),"w",encoding="utf-8") as f: f.write(STYLE)
          def main():
              ensure()
              print("OK: basic builder (placeholder)")
          if __name__=="__main__": main()
          PY
          fi

          # 기본 keywords.csv 없으면만 생성
          if [ ! -f content/keywords/keywords.csv ]; then
            cat > content/keywords/keywords.csv << 'CSV'
          keyword,subtopic,intent
          시험 공부 플래너,중학생용,informational
          수학 공식 정리 프린트,중학 수학,informational
          영어 단어 암기표,주 100단어,transactional
          CSV
          fi

          # docs/style.css는 아가씨 코드가 덮어쓰므로 여기선 생성 안 함
          echo "Prep done (no overwrite)"; ls -la site_generator; ls -la docs

      - name: Generate posts
        run: python site_generator/generate_posts.py

      - name: Build site
        run: python site_generator/build_site.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "auto(self-heal no-overwrite): build $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
